dirty_table: [-0.87007836938980498, 1.6648371322372628, 2.3132298229238111]
shelf: [0.41857172254069575, 1.34384098789189, 1.6028478528804446]
table_bottom_edge: [0, 0, 0]
table_left_edge: [0.72007650818912594, -0.90681776102733136, 1.5484268495421882]
table_top_edge: [-0.22023971669684614, 0.029499547665250234, 0.011226247974783428]
table_right_edge: [0.53835639676131619, 0.91548461840358408, -1.4665079411106547]
rotating_table: [-0.684, -0.633 -2.277]

start: [0.1833312550106456, 0.5398178171099393, -2.863603837801871]
table_putdown_top: [0.372, 0.00, 1.09]
table_putdown_bottom: [-1.85, 0.11, .90]
dirty_table_putdown: [-1.2, 2.04, 0.995]

